{{- if not .Values.useSecretsManager }}
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: {{ .Values.messagingNamespace }}
type: Opaque
stringData:
  postgres-username: "{{ .Values.dbUsername }}"
  postgres-password: "{{ .Values.dbPassword }}"
  access_token: "{{ .Values.accessToken }}"
{{- end }}
