{{- if .Values.deployInternalMessagingRedis }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: messaging-redis-pvc
  labels:
    app: redis
  namespace: {{ .Values.messagingNamespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: redis
{{- end }}
